spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruitshop?serverTimezone=GMT%2B8
    username: root
    password: xiang03040059
    driver-class-name: com.mysql.cj.jdbc.Driver
server:
  port: 9090
mybatis:
  mapper-locations: classpath:/mapper/**.xml
